# Generated by Django 2.2 on 2019-09-12 09:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('user_role', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=250)),
                ('client_name', models.CharField(max_length=250)),
                ('client_contact', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='IssueTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_people_impacted', models.CharField(max_length=250)),
                ('issue_title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('urgency', models.CharField(max_length=250)),
                ('priority_reason', models.CharField(max_length=250)),
                ('submission_comments', models.CharField(max_length=250)),
                ('issue_type', models.CharField(max_length=250)),
                ('attachments', models.FileField(upload_to='issues')),
                ('status', models.CharField(max_length=250)),
                ('next_party', models.CharField(max_length=250)),
                ('status_reason', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_tickets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=250)),
                ('project_description', models.CharField(max_length=250)),
                ('attachments', models.FileField(upload_to='projects')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'db_table': 'project_clients',
            },
        ),
        migrations.CreateModel(
            name='PerformedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affected_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.IssueTicket')),
                ('affected_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performed_actions',
            },
        ),
        migrations.AddField(
            model_name='issueticket',
            name='project_with_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Project'),
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('attachments_file', models.FileField(null=True, upload_to='issue_attachments')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IssueTicket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_comments',
            },
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affected_column', models.CharField(max_length=200, null=True)),
                ('old_value', models.CharField(max_length=200, null=True)),
                ('new_value', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affected_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('edit_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edit_logs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Client'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
