# Generated by Django 2.2 on 2019-09-12 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190912_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
