# Generated by Django 2.2 on 2019-09-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attachments',
        ),
    ]
